version: "3.8"

services:
  scraper-api:
    restart: always
    build: 
      dockerfile: ./Scraper.Api/Dockerfile
      context: ./services
    env_file: local.env
    ports: 
      - 8080:80
  scraper-service:
    restart: always
    build: 
      dockerfile: ./Scraper.Service/Dockerfile
      context: ./services
    env_file: local.env
  scraper-processor:
    restart: always
    build: 
      dockerfile: ./Scraper.Service.Processor/Dockerfile
      context: ./services
    env_file: local.env
  web:
    build: ./web
  rabbit:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
  mongo: 
    image: mongo
    ports:
      - 27017:27017
  redis: 
    image: redis