version: "3.8"

services:
  scraper-api:
    restart: always
    build: 
      dockerfile: ./Scraper.Api/Dockerfile
      context: ./services
    env_file: local.env
    ports: 
      - 8080:80
  scraper-service:
    restart: always
    build: 
      dockerfile: ./Scraper.Service/Dockerfile
      context: ./services
    env_file: local.env
    ports: 
      - 8081:80
  web:
    build: ./web
  rabbit:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
  mongo: 
    image: mongo
    ports:
      - 27017:27017
  redis: 
    image: redis
  zookeeper:
    image: zookeeper
    restart: always
  nimbus:
    image: storm
    command: storm nimbus
    depends_on:
      - zookeeper
    restart: always
    ports:
      - 6627:6627
  supervisor:
    image: storm
    command: storm supervisor
    depends_on:
      - nimbus
      - zookeeper
    restart: always
  storm-ui:
    ports: 
      - 8090:8080
    image: storm
    command: storm ui
    depends_on:
      - nimbus
      - zookeeper
    restart: always    