type ScraperSource{
	id: ID!
	collector: Collector!
}

type WebCollector{
	target: String!
}

union Collector = WebCollector

type Query{
	source(
		id: ID!
	): ScraperSource!
	sources(skip: Int = 0, take: Int = 50): [ScraperSource!]!
}

input WebCollectorInput{
	target: String!
}


type Mutation{
	createWebSource(
		source: WebCollectorInput!
	): String!
}
schema{
	query: Query,
	mutation: Mutation
}
