name: Lint Web

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: NPM Install
      working-directory: ./web
      run: npm i
    - name: Lint
      working-directory: ./web
      run: npm run lint:fix